// Machine code generated by CMPE220 Assembler
// Total instructions: 8

word_t program[] = {
    0x1004,  // [0]     MOV R0, 4       ; start with n = 4
    0xA003,  // [1]     CALL func       ; call func(n)
    0xC000,  // [2]     HALT            ; when recursion is done, halt the CPU
    0x3000,  // [3]     SUB R0, 0       ; ALU out = R0, sets ZR flag if R0 == 0
    0x9007,  // [4]     JZ end_func     ; if zero flag set, go to RET
    0x3001,  // [5]     SUB R0, 1       ; decrement R0
    0xA003,  // [6]     CALL func
    0xB000  // [7]     RET
};

int program_size = 8;
